#title in header
title: "Hi there!"

#main info
#owner
owner: "I am Hsueh-Ya (Alee), Tsai"
email: aleetsaiya@gmail.com
info: "A Computer Science student who wants to be a Front-End engineer from Taiwan.ğŸ‘¨â€ğŸ’»"
#description
desc: "This is my coding blog. I will share my learning experience about coding on this site. You can visit About page if you want to know more about me, hope you enjoy! ğŸ˜"

#menu
menu:
  Works: /Works
  About: /About

#index/main page max show posts (in number)
max_post: 5

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Taiwan
placelink: https://en.wikipedia.org/wiki/Taiwan
github: https://github.com/aleetsaiya
linkedin: https://www.linkedin.com/in/alee-tsai/
twitter: https://twitter.com/Alee_ba_ba

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: https-aleetsaiya-github-io